spring:
  redis:
    host: 192.168.56.101
    port: 6379
    timeout: 3000
  datasource:
    name: Oracle
    url:  jdbc:oracle:thin:@//10.128.90.178/crmtestdb
    username: sales_app
    password: sales_app
    driver-class-name: oracle.jdbc.OracleDriver
    #type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: appuser
        format_sql: true
        dialect: org.hibernate.dialect.Oracle10gDialect

mybatis:
  # 重要配置
  type-aliases-package: com.lin.domain
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:log4j2-dev.xml


application:
  pic_HttpIP: http://42.99.16.145:19491
 #sc
 #pic_HttpIP=http://42.99.16.176:19491
 #生成群组头像 图片 暂存地址 群组中所有人的头像地址
  pic_group_temp_img: /cfiles/sales/appkms/2/public/addresslist/group/temp/
 #pic_group_temp_img=E:\\test\\
 #群组头像生成完成 保存到服务器地址
  pic_group_img: /cfiles/sales/appkms/2/public/addresslist/group/
 #pic_group_img=E:\\test\\
 #保存数据库地址
  pic_group_db_img: /2/public/addresslist/group/
 #pic_group_db_img=E:\\test\\
 #拷贝图像 补全文件路径
  pic_group_db_img_root: /cfiles/sales/appkms
 #体验
  sales_integral_add_score: http://10.128.49.65:20060/sales-integral/common/addScore
 #体验
  ADDB_DK: http://10.128.90.164:9080/CRM-PAD/services/SalesPAD?wsdl
 #测试  图片地址
  CUST_IMG: http://42.99.16.145/mpi/plist_dir/plist_dir/custLogo/150_noword/
  redis_host: 10.1.11.32
  redis_port: 6379
  redis_timeout: 30000
  enterprise:
    createGroup:
    inviteFriend:
    removeMembers:
    exitGroup:
    dissolution:
    modify:
    queryGroup:
swagger:
  show: true