spring:
  redis:
    host: 10.1.11.32
    port: 6379
    timeout: 30000
  datasource:
    name: Oracle
    url:  jdbc:oracle:thin:@//10.128.49.65:56128/saleshdb
    username: sales_app
    password: sales_app
    driver-class-name: oracle.jdbc.OracleDriver
    #type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: appuser
        format_sql: true
        dialect: org.hibernate.dialect.Oracle10gDialect

mybatis:
  # 重要配置
  type-aliases-package: com.lin.domain
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:log4j2-test.xml

application:
  pic_HttpIP: http://42.99.16.145:19491
  #生成群组头像 图片 暂存地址 群组中所有人的头像地址
  pic_group_temp_img: /cfiles/sales/appkms/2/public/addresslist/group/temp/
  #pic_group_temp_img=E:\\test\\
  #群组头像生成完成 保存到服务器地址
  pic_group_img: /cfiles/sales/appkms/2/public/addresslist/group/
  #pic_group_img=E:\\test\\
  #保存数据库地址
  pic_group_db_img: /2/public/addresslist/group/
  #pic_group_db_img=E:\\test\\
  #拷贝图像 补全文件路径
  pic_group_db_img_root: /cfiles/sales/appkms
  #体验
  sales_integral_add_score: http://10.128.49.65:20060/sales-integral/common/addScore
  #体验
  ADDB_DK: http://10.128.49.81:9083/CRM-PAD/services/SalesPAD?wsdl
  #测试  图片地址
  CUST_IMG: http://42.99.16.145/mpi/plist_dir/plist_dir/custLogo/150_noword/
  redis_host: 10.1.11.32
  redis_port: 6379
  redis_timeout: 30000
  enterprise:
    createGroup: http://10.128.49.65:20060/enterprise_go/group/createGroup
    inviteFriend: http://10.128.49.65:20060/enterprise_go/customer/inviteFriend
    removeMembers: http://10.128.49.65:20060/enterprise_go/group/removeMembers
    exitGroup: http://10.128.49.65:20060/enterprise_go/group/exitGroup
    dissolution: http://10.128.49.65:20060/enterprise_go/group/dissolution
    modify: http://10.128.49.65:20060/enterprise_go/group/modify
    queryGroup: http://10.128.49.65:20060/enterprise_go/group/queryGroup
    updateGroupInfo: http://10.128.49.65:20060/enterprise_go/group/updateGroupInfo
    save2OutGroup: http://10.128.49.65:20060/enterprise_go/group/save2OutGroup
feign:
  hystrixConfig:
    "hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds": 18000
  endpointConfig:
    CrowdConnector:
      default:
        url: http://10.128.49.65:20060
        readTimeoutMillis: 18000
        connectTimeoutMillis: 15000
swagger:
  show: true