spring:
  datasource:
    name: Oracle
    url:  jdbc:oracle:thin:@//10.128.32.5:3436/uamdb
    username: jtuam
    password: fdc97354
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: jtuam
        format_sql: true
        dialect: org.hibernate.dialect.Oracle10gDialect
  thymeleaf:
    cache: false


#生产上关闭 swagger
swagger:
  show: false