spring:
  datasource:
    name: Oracle
    url:  jdbc:oracle:thin:@//10.128.32.5:3436/uamdb
    username: jtuam
    password: fdc97354
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: jtuam
        format_sql: true
        dialect: org.hibernate.dialect.Oracle10gDialect
  thymeleaf:
    cache: false
    
application:
 #生产
 sales_integral_add_score=/sales-integral/common/addScore
 #生产
 ADDB_DK: http://10.128.87.58:8101/CRM-PAD/services/SalesPAD?wsdl
 #生产  图片地址
 CUST_IMG: http://42.99.16.176/mpi/plist_dir/plist_dir/custLogo/150_noword/
 
#生产上关闭 swagger
swagger:
  show: false